name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    outputs:
      functionAppName: ${{ steps.deploy.outputs.functionAppName }}
    steps:
      - uses: actions/checkout@v7

      - uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/bicep-deploy@v2
        id: deploy
        with:
          type: deployment
          operation: create
          scope: resourceGroup
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template-file: ./.bicep/main.bicep
          parameters: |
            {
              "discordPublicKey": "${{ secrets.DISCORD_PUBLIC_KEY }}",
              "discordBotToken": "${{ secrets.DISCORD_BOT_TOKEN }}"
            }

  deploy-code:
    needs: deploy-infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'

      - run: dotnet publish Q2.App/Q2.App.csproj -c Release -r linux-x64 -o ./publish

      - uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: Azure/functions-action@v1
        with:
          app-name: ${{ needs.deploy-infra.outputs.functionAppName }}
          package: ./publish
